/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarSelectionPanel: typeof import('./src/components/CarSelectionPanel.vue')['default']
    HeaderFilter: typeof import('./src/components/HeaderFilter.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    OrderListCard: typeof import('./src/components/OrderListCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StyleModelPickerDrawer: typeof import('./src/components/StyleModelPickerDrawer.vue')['default']
    Swiper: typeof import('./src/components/Swiper.vue')['default']
    TgBackButton: typeof import('./src/components/TgBackButton.vue')['default']
    TgButton: typeof import('./src/components/TgButton.vue')['default']
    TgFilepond: typeof import('./src/components/TgFilepond.vue')['default']
    TgSelect: typeof import('./src/components/TgSelect.vue')['default']
    TgSwitch: typeof import('./src/components/TgSwitch.vue')['default']
  }
}
